### ISSUE TITLE
部署的时候出现错误

### ISSUE THREAD

**Issue by Adamcrg** [msgbyte/tailchat-meeting#1]
![image](https://user-images.githubusercontent.com/34224261/176614556-c88a0374-0208-4fe2-8225-b5bb61a3184d.png)

server:ERROR:promClient TypeError: RegisterAggregated is not a function at default_1 (/tailchat-meeting/server/dist/lib/stats/promExporter.js:31:36)

**Comment by moonrailgun** [comment]
麻烦拉下最新代码再看一下呢？

**Comment by Adamcrg** [comment]
更新了代码可以了，感谢老哥。
