### ISSUE TITLE
我按照文档部署了之后 无法播放 

### ISSUE THREAD

**Issue by Adamcrg** [msgbyte/tailchat-meeting#2]
参考
![image](https://user-images.githubusercontent.com/34224261/177515315-ae98458f-6c6d-42b4-b4ef-b0b37ad44a38.png)

**Comment by moonrailgun** [comment]
没有理解是想播放什么？

我试了一下非常work

**Comment by Adamcrg** [comment]
> 

我开启了摄像头，本地是可以看见的，再开一个页签进入无法看到视频的数据，只会显示一个黑色的

**Comment by moonrailgun** [comment]
我看你没有开放媒体服务的端口。你需要开放 40000 到 49999的端口(默认)才行，这是用于webrtc的媒体转发服务端口

**Comment by Adamcrg** [comment]
> 我看你没有开放媒体服务的端口。你需要开放 40000 到 49999的端口(默认)才行，这是用于webrtc的媒体转发服务端口

感谢，我开放之后可以了。

**Comment by moonrailgun** [comment]
文档已补充，之前漏了, 感谢提醒
https://tailchat.msgbyte.com/docs/meeting/deployment
