### ISSUE TITLE
浏览器访问提示浏览器没有必要的功能

### ISSUE THREAD

**Issue by rickZhanghenan** [msgbyte/tailchat-meeting#4]
![C1E5D342-C226-41E8-AF3E-9E2DF690E13C](https://user-images.githubusercontent.com/38641592/197837152-26d39e52-b9cb-4dd7-83e9-d5d75448dd05.jpeg)

**Comment by moonrailgun** [comment]
![image](https://user-images.githubusercontent.com/6964737/197920692-4efc5f65-476f-4149-9634-2702db3d94d4.png)
我找了一张ios的safari版本列表，辛苦看一下你的设备ios版本是否符合 safari 12以上版本？

**Comment by rickZhanghenan** [comment]
我记得safari版本跟系统版本一致的吧，我是iPhone7p目前系统是ios15.5，如果是的话那我safari版本也是15吧

**Comment by moonrailgun** [comment]
我用云真机模拟了一下好像没有问题。

找不到7p的ios15版本。用的是8的v15.3

![image](https://user-images.githubusercontent.com/6964737/198515656-a9370b27-2bea-4901-99c7-6df5717f11c0.png)

这个错误主要是无法获取到webrtc服务造成的。(无法访问 `navigator.mediaDevices.getUserMedia` 或 `window.RTCPeerConnection`)

**Comment by rickZhanghenan** [comment]
我记得safari的版本是和ios一致的吧，我是iphone7p的15.5版本，如果一致的话应该safari也是15.5吧，chrome版本是107.0.5304.88，访问时也是同样提示

**Comment by rickZhanghenan** [comment]
那我再去找找原因，十分感谢指点

**Comment by moonrailgun** [comment]
也感谢你的反馈
