### ISSUE TITLE
总是提示无法进入房间

### ISSUE THREAD

**Issue by hm-Private** [msgbyte/tailchat-meeting#5]
大佬可以帮我看看啥问题吗

**Comment by hm-Private** [comment]
[root@ser999805290083 ~]# netstat -aptn
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN      21878/php-fpm: mast 
tcp        0      0 0.0.0.0:13001           0.0.0.0:*               LISTEN      21588/tailchat-meet 
tcp        0      0 0.0.0.0:6379            0.0.0.0:*               LISTEN      21128/redis-server  
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      1/systemd           
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      21876/nginx: master 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      3648/sshd           
tcp        0      0 0.0.0.0:8889            0.0.0.0:*               LISTEN      21588/tailchat-meet 
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      3504/master         
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      21876/nginx: master 
tcp        0      0 10.0.32.4:443           103.135.103.180:36255   ESTABLISHED 21900/nginx: worker 
tcp        0      0 127.0.0.1:33670         127.0.0.1:6379          ESTABLISHED 21588/tailchat-meet 
tcp        0      0 127.0.0.1:47398         127.0.0.1:13001         TIME_WAIT   -                   
tcp        0      0 127.0.0.1:47406         127.0.0.1:13001         TIME_WAIT   -                   
tcp        0      0 127.0.0.1:47394         127.0.0.1:13001         TIME_WAIT   -                   
tcp        0      0 127.0.0.1:13001         127.0.0.1:47402         TIME_WAIT   -                   
tcp        0      0 127.0.0.1:47396         127.0.0.1:13001         TIME_WAIT   -                   
tcp        0      0 127.0.0.1:47392         127.0.0.1:13001         TIME_WAIT   -                   
tcp        0      0 127.0.0.1:47402         127.0.0.1:13001         TIME_WAIT   -                   
tcp        0      0 127.0.0.1:47390         127.0.0.1:13001         TIME_WAIT   -                   
tcp        0      0 127.0.0.1:47400         127.0.0.1:13001         TIME_WAIT   -                   
tcp        0      0 127.0.0.1:47404         127.0.0.1:13001         TIME_WAIT   -                   
tcp        0      0 10.0.32.4:22            103.135.103.180:37225   ESTABLISHED 27764/sshd: root@pt 
tcp        0      0 127.0.0.1:6379          127.0.0.1:33670         ESTABLISHED 21128/redis-server  
tcp6       0      0 :::6379                 :::*                    LISTEN      21128/redis-server  
tcp6       0      0 :::111                  :::*                    LISTEN      1/systemd           
tcp6       0      0 :::80                   :::*                    LISTEN      21876/nginx: master 
tcp6       0      0 :::22                   :::*                    LISTEN      3648/sshd           
tcp6       0      0 ::1:25                  :::*                    LISTEN      3504/master         
tcp6       0      0 :::443                  :::*                    LISTEN      21876/nginx: master

**Comment by hm-Private** [comment]
[](url)
![微信截图_20221204150815](https://user-images.githubusercontent.com/67125126/205478915-669b0d96-2985-44ba-a78c-9ec09c972a25.png)
![微信截图_20221204150837](https://user-images.githubusercontent.com/67125126/205478916-f90cf5df-ec7e-443e-a837-144760c93375.png)
![微信截图_20221204150911](https://user-images.githubusercontent.com/67125126/205478918-b8cf44f2-9e9d-49f6-bd88-ded7d6456b15.png)
大佬,这40000端口就是不显示打开,无法进入房间

**Comment by hm-Private** [comment]
大佬,能帮忙看看吗,参考:https://hmstnt.gq/

**Comment by hm-Private** [comment]
大佬

**Comment by hm-Private** [comment]
我都怀疑是vps的问题了

**Comment by moonrailgun** [comment]
你这地址也访问不了啊

**Comment by hm-Private** [comment]
https://github.com/msgbyte/tailchat-meeting/issues/5#issuecomment-1336384707
我又换了一台和你一样的新加坡腾讯云,稍等下,可能是之前的vps问题

**Comment by hm-Private** [comment]
![微信截图_20221204192758](https://user-images.githubusercontent.com/67125126/205487871-007ba442-24f3-429a-bf12-72f431a9dcff.png)
![微信截图_20221204192820](https://user-images.githubusercontent.com/67125126/205487874-22285164-ae81-4f58-8a68-74db9200c3e9.png)
刚整,不知道行不行了

**Comment by moonrailgun** [comment]
不要暴露6379端口啊，很危险的。

**Comment by hm-Private** [comment]
现在不光这个问题,我现在搭建都无法实现

**Comment by hm-Private** [comment]
这套程序好像认服务器么?我现在一堆问题,

**Comment by moonrailgun** [comment]
不认，docker存在的意义就是就是减少程序与系统差异带来的不同。

首先在你自己的服务器上访问自己本地的443端口(https)是否联通，
然后再检查是否能够通过外部访问。

**Comment by hm-Private** [comment]
![微信截图_20221204200912](https://user-images.githubusercontent.com/67125126/205489651-72ff72aa-a5eb-4977-b363-4d205021111b.png)
我用疼腾讯新加坡,现在又出现这个问题,始终过不去,系统	
CentOS 7.6 64bit

**Comment by moonrailgun** [comment]
> ![微信截图_20221204200912](https://user-images.githubusercontent.com/67125126/205489651-72ff72aa-a5eb-4977-b363-4d205021111b.png) 我用疼腾讯新加坡,现在又出现这个问题,始终过不去,系统 CentOS 7.6 64bit

看起来是内存不够导致无法编译。可以参考一下我的这篇文章
http://moonrailgun.com/posts/6769ba51/

**Comment by hm-Private** [comment]
大佬,还是不行 你帮我看看 https://hmstnt.ga/)

**Comment by hm-Private** [comment]
进不去房间,立马就退出来

**Comment by hm-Private** [comment]
![微信截图_20221204211911](https://user-images.githubusercontent.com/67125126/205492812-db06b42a-be36-4143-b9fb-d983d0620fa8.png)
扫描端口显示关闭的
![微信截图_20221204212007](https://user-images.githubusercontent.com/67125126/205492844-ee774077-06c8-4909-af83-4865bd70e49a.png)
可是我再腾讯云后台是开启的

**Comment by hm-Private** [comment]
操作系统	
CentOS 7.6 64bit

我用的这系统,是不是系统问题啊

**Comment by hm-Private** [comment]
![微信截图_20221204212445](https://user-images.githubusercontent.com/67125126/205493037-1d378fff-cbf6-4a40-979c-a9da8536b2f0.png)
看机器端口也没有40000-49999

**Comment by hm-Private** [comment]
大佬在不

**Comment by hm-Private** [comment]
就是40000端口没开,其他都显示开启,是不是有啥不知道的问题哈

**Comment by hm-Private** [comment]
![微信截图_20221204213939](https://user-images.githubusercontent.com/67125126/205493783-1be96cbd-eb42-4062-9cf7-cba7562ecf27.png)

**Comment by moonrailgun** [comment]
> ![微信截图_20221204192820](https://user-images.githubusercontent.com/67125126/205487874-22285164-ae81-4f58-8a68-74db9200c3e9.png) 

这个问题是rtc服务没有连接上。把udp协议也开放试试呢？

**Comment by hm-Private** [comment]
![微信截图_20221204215204](https://user-images.githubusercontent.com/67125126/205494457-45423502-2ca4-4c77-bb30-d1ee1bfc42c9.png)
都开了
还是 一样 缓存我也清理了,就差重启服务器 零零

**Comment by hm-Private** [comment]
![微信截图_20221204220831](https://user-images.githubusercontent.com/67125126/205495268-d0e63d8a-c81e-4fe0-b4e5-822b33ef6b2a.png)
https://hmstnt.gq/

这是中午的一台机器,一样是相同的问题,死活进不去,端口都是开启的

**Comment by moonrailgun** [comment]
我看了一下你websocket的服务都没连上啊。辛苦检查一下反向代理的配置，让你的代理能够支持websocket

可以看一下这篇文档: https://tailchat.msgbyte.com/docs/deployment/troubleshooting#websocket-%E8%BF%9E%E6%8E%A5%E8%AE%BF%E9%97%AE%E4%B8%8D%E6%AD%A3%E7%A1%AE%E8%A1%A8%E7%8E%B0%E5%BD%A2%E5%BC%8F%E6%98%AF%E5%8F%AF%E4%BB%A5%E6%B3%A8%E5%86%8C%E4%BD%86%E6%98%AF%E6%97%A0%E6%B3%95%E6%89%93%E5%BC%80%E4%B8%BB%E7%95%8C%E9%9D%A2

**Comment by hm-Private** [comment]
![微信截图_20221204221715](https://user-images.githubusercontent.com/67125126/205495723-32f99806-047e-4c64-bc62-2ab42aa5a2bd.png)
这个怎么修改都不会,这个小白没法玩啊

**Comment by hm-Private** [comment]
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2 default_server;

    # enable subfolder method reverse proxy confs
    include /config/nginx/proxy-confs/*.subfolder.conf;

    # all ssl related config moved to ssl.conf
    include /config/nginx/ssl.conf;

    # server
    location ~ ^/(socket\.io) {
        proxy_pass http://tailchat-meeting:13001;
        #
        proxy_http_version 1.1;
        proxy_redirect off;
        proxy_request_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 86400;
        proxy_set_header Referer $http_referer;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_max_temp_file_size 2048m;
    }

    # app
    location ~ ^/(sockjs-node) {
        proxy_pass http://tailchat-meeting:13001;
        #
        proxy_http_version 1.1;
        proxy_redirect off;
        proxy_request_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 86400;
        proxy_set_header Referer $http_referer;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_max_temp_file_size 2048m;
    }

    location / {
        proxy_pass http://tailchat-meeting:13001;
    }
}

**Comment by hm-Private** [comment]
大佬这个怎么修改啊

**Comment by hm-Private** [comment]
大佬指导下修改哈!

**Comment by moonrailgun** [comment]
我在开一台新机器在看，因为我发现如果你用我给的配置的话应该是已经配好的了，不需要任何修改

**Comment by hm-Private** [comment]
好的，那就是我需要重新安装吗？

**Comment by moonrailgun** [comment]
我大概知道是什么原因了，因为腾讯云的网络是弹性绑定的，所以公网ip他其实是检测不到的(无法绑定网卡)。

所以对于国内服务商需要将环境变量设为内网ip才可以（一般为网卡eth0的ip）

*docker-compose.env*
```
MEDIASOUP_IP=10.0.x.x(你的内网ip)
```

然后再执行`docker compose up -d `重启应用

**Comment by hm-Private** [comment]
确实腾讯云换下内网ip就可以了，那是不是其他服务商的机器也一样，换下内网ip

**Comment by moonrailgun** [comment]
> 确实腾讯云换下内网ip就可以了，那是不是其他服务商的机器也一样，换下内网ip

对于弹性网络是这样的，提供类似服务的机器外网ip不会写到网卡上。

**Comment by moonrailgun** [comment]
这个问题我close了
