### ISSUE TITLE
构建镜像出现错误

### ISSUE THREAD

**Issue by Surely0402** [msgbyte/tailchat-meeting#7]
涉及到我的知识盲区了....
![image](https://user-images.githubusercontent.com/52198484/210569200-14cf4143-1fdb-48d5-af0f-eb3786e53f32.png)

**Comment by moonrailgun** [comment]
已修复，辛苦拉下最新代码重新编译一下。这边因为在做一个特效不小心把没有准备好的代码给加到安装过程中了。

这个issue我先close了，如果还有问题请随时重新打开

**Comment by Surely0402** [comment]
install可以了, build出问题了, 百度也没找到解决方法,我太菜了...
![image](https://user-images.githubusercontent.com/52198484/210689006-6d0464ea-8a3a-48ea-8834-2c6a288f3085.png)

**Comment by Surely0402** [comment]
> 已修复，辛苦拉下最新代码重新编译一下。这边因为在做一个特效不小心把没有准备好的代码给加到安装过程中了。
> 
> 这个issue我先close了，如果还有问题请随时重新打开

install可以了, build出问题了, 百度也没找到解决方法,我太菜了...
![image](https://user-images.githubusercontent.com/52198484/210708008-2924dfec-cdf6-417f-8387-d6e6c3a95400.png)

**Comment by moonrailgun** [comment]
抱歉，我正在处理最新分支上关于依赖关系的问题，这需要一些时间。我不知道为什么会产生错乱的依赖关系引用，因此我打算全部升级一遍。

当然，对你来说无关紧要。因为最新的代码不会带来任何变更。建议切到一个比较老的分支来消除这段时间产生的问题。

`e73256b216e072a11fe7451af6762d947901df57`

你可以使用如下命令来切换到特定的源码版本

```bash
git checkout e73256b216e072a11fe7451af6762d947901df57
cd compose && docker compose build
```

我已经做过测试，这个commit是可以正常被编译的。很抱歉改动对你带来的影响，在后续我会考虑引入一些质量保证服务确保改动不会产生问题

**Comment by Surely0402** [comment]
> 抱歉，我正在处理最新分支上关于依赖关系的问题，这需要一些时间。我不知道为什么会产生错乱的依赖关系引用，因此我打算全部升级一遍。
> 
> 当然，对你来说无关紧要。因为最新的代码不会带来任何变更。建议切到一个比较老的分支来消除这段时间产生的问题。
> 
> `e73256b216e072a11fe7451af6762d947901df57`
> 
> 你可以使用如下命令来切换到特定的源码版本
> 
> ```shell
> git checkout e73256b216e072a11fe7451af6762d947901df57
> cd compose && docker compose build
> ```
> 
> 我已经做过测试，这个commit是可以正常被编译的。很抱歉改动对你带来的影响，在后续我会考虑引入一些质量保证服务确保改动不会产生问题

好的,大佬.实在麻烦了.
