### ISSUE TITLE
{$Path}/compose/config/里网关端口配置问题.

### ISSUE THREAD

**Issue by Surely0402** [msgbyte/tailchat-meeting#8]
大佬,不好意思又来打扰了,最新版本代码没有构建问题了.
目前测试中发现nginx.conf修改监听的80和443端口后, web首页可访问, 在输入会议号及名称后点击加入, 调用的/api和/auth等接口时, 默认还是80端口, 就会出现链接超时无法加入会议的问题.

**Comment by moonrailgun** [comment]
你是改端口了是嘛？改端口的话记得这里也改下 `compose/config/app-config.js` 的 `productionPort`字段

**Comment by Surely0402** [comment]
> 你是改端口了是嘛？改端口的话记得这里也改下 `compose/config/app-config.js` 的 `productionPort`字段

这个改了就对了. 多谢大佬.
