### ISSUE TITLE
docker compose构建时报错

### ISSUE THREAD

**Issue by zjmdong** [msgbyte/tailchat-meeting#9]
在centos7上尝试多次，试过重装系统和在云服务器上安装，报错基本一致。完全按照文档的方法进行的安装。不知是由于系统问题还是依赖没有安装对？比较小白涉及到知识盲区了，望大佬解答！谢谢！
![image](https://github.com/msgbyte/tailchat-meeting/assets/90539586/73ba830f-3e29-4709-88bb-111c0788f697)![屏幕截图 2023-07-06 224842](https://github.com/msgbyte/tailchat-meeting/assets/90539586/64aff793-4f1a-4df2-a84e-60f4e0dcdbf9)

**Comment by zjmdong** [comment]
![屏幕截图 2023-07-06 225221](https://github.com/msgbyte/tailchat-meeting/assets/90539586/30ed7a93-bf14-4ffa-8727-7a1abb1550d3)
上面不小心传了两张一样的图，这张的报错也是细微的区别

**Comment by moonrailgun** [comment]
内存不够，建议用官方镜像

截图报错很明显告知你 out of memory, 即OOM

**Comment by moonrailgun** [comment]
哦不好意思看错项目了，tailchat-meeting没有提供官方镜像，建议你增加内存，1g配置也太小了

**Comment by zjmdong** [comment]
大佬，2g和4g内存的机器我也试过，报错同理

**Comment by zjmdong** [comment]
试了下6g内存的机器，现在可以了，麻烦大佬了

**Comment by moonrailgun** [comment]
我的服务是部署在一台2核2G的服务器上的，你可以尝试使用swap来优化临时情况下的内存调用。因为就编译的时候需要，运行时不用这么多资源

![image](https://github.com/msgbyte/tailchat-meeting/assets/6964737/124d3de4-051d-491e-8c88-9305c832f770)
